package com.testDynamoDB.testDynamoDB.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "profile")
public class Profile {
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBRangeKey(attributeName= "profile_id")
	public String profile_id;
	
	@DynamoDBHashKey(attributeName = "user_id")
	public String user_id;
	
	public String profile_configurations;
	public String profile_name;
	public String updated_date;
	public String operating_system;
	public String language;
	public String idle_timer;
	public String logo_content_id;
	public String segment_id;
	public String promotional_content_id;
	public String banner_carousel_id;
	public String price_content_id;
	public String attract_loop_id;
	
	public String getProfile_id() {
		return profile_id;
	}
	public void setProfile_id(String profile_id) {
		this.profile_id = profile_id;
	}
	public String getUser_id() {
		return user_id;
	}
	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}
	public String getProfile_configurations() {
		return profile_configurations;
	}
	public void setProfile_configurations(String profile_configurations) {
		this.profile_configurations = profile_configurations;
	}
	public String getProfile_name() {
		return profile_name;
	}
	public void setProfile_name(String profile_name) {
		this.profile_name = profile_name;
	}
	public String getUpdated_date() {
		return updated_date;
	}
	public void setUpdated_date(String updated_date) {
		this.updated_date = updated_date;
	}
	public String getOperating_system() {
		return operating_system;
	}
	public void setOperating_system(String operating_system) {
		this.operating_system = operating_system;
	}
	public String getLanguage() {
		return language;
	}
	public void setLanguage(String language) {
		this.language = language;
	}
	public String getIdle_timer() {
		return idle_timer;
	}
	public void setIdle_timer(String idle_timer) {
		this.idle_timer = idle_timer;
	}
	public String getLogo_content_id() {
		return logo_content_id;
	}
	public void setLogo_content_id(String logo_content_id) {
		this.logo_content_id = logo_content_id;
	}
	public String getSegment_id() {
		return segment_id;
	}
	public void setSegment_id(String segment_id) {
		this.segment_id = segment_id;
	}
	public String getPromotional_content_id() {
		return promotional_content_id;
	}
	public void setPromotional_content_id(String promotional_content_id) {
		this.promotional_content_id = promotional_content_id;
	}
	public String getBanner_carousel_id() {
		return banner_carousel_id;
	}
	public void setBanner_carousel_id(String banner_carousel_id) {
		this.banner_carousel_id = banner_carousel_id;
	}
	public String getPrice_content_id() {
		return price_content_id;
	}
	public void setPrice_content_id(String price_content_id) {
		this.price_content_id = price_content_id;
	}
	public String getAttract_loop_id() {
		return attract_loop_id;
	}
	public void setAttract_loop_id(String attract_loop_id) {
		this.attract_loop_id = attract_loop_id;
	}


}
