package com.testDynamoDB.testDynamoDB.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "student")
public class Student {
	
	
//	@DynamoDBAutoGeneratedKey
	 @DynamoDBHashKey(attributeName = "studentId")
    private Long studentId;
	 
	@DynamoDBAttribute
    private String firstName;
	
	@DynamoDBAttribute
    private String lastName;

    public Student(){}

    public Student(Long studentId, String firstName, String lastName) {
        this.studentId = studentId;
        this.firstName = firstName;
        this.lastName = lastName;
    }

   
    public Long getStudentId() {
        return studentId;
    }

    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

//    @DynamoDBRangeKey(attributeName = "firstName")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

	/* @DynamoDBRangeKey(attributeName = "lastName") */
    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) { this.lastName = lastName; }
}